using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/* 
 * Written this semester, starting at line 12.
 * Holds helpfull info using static properties, for all scripts to use.
 */
//This one line was generated by unity
public class HelpfulInfo : MonoBehaviour
{
    public static List<GameObject> SpawnPlaces;
    public List<GameObject> spawnPlaces;

    //When the game starts, set the non-static properties to their static counter parts.
    void Awake()
    {
        SpawnPlaces = spawnPlaces; 
    }
}
